USE PawPalsDB;
DROP TABLE IF EXISTS ReportedPosts;
DROP TABLE IF EXISTS Reaction;
DROP TABLE IF EXISTS BannedUsers;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
	UserID INT IDENTITY(1, 1) PRIMARY KEY,
	Username NVARCHAR(25) UNIQUE NOT NULL,
	Email NVARCHAR(100) UNIQUE NOT NULL,
	Pwd NVARCHAR(MAX) NOT NULL,
	Country NVARCHAR(30),
	City NVARCHAR(50),
	FullName NVARCHAR(100),
	ProfilePic VARBINARY(MAX)
);
CREATE TABLE Posts (
	PostID INT IDENTITY(1, 1) PRIMARY KEY,
	UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
	Likes INT NOT NULL,
	Dislikes INT NOT NULL,
	Img VARBINARY(MAX) NOT NULL,
	UploadDate DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE TABLE ReportedPosts (
	PostID INT FOREIGN KEY REFERENCES Posts(PostID) ON DELETE NO ACTION,
	Reporter INT FOREIGN KEY REFERENCES Users(UserID) ON DELETE NO ACTION,
	Cat INT NOT NULL,
	CONSTRAINT ReportPK PRIMARY KEY (PostID, Reporter)
);
CREATE TABLE Reaction (
	PostID INT FOREIGN KEY REFERENCES Posts(PostID) ON DELETE NO ACTION,
	UserID INT FOREIGN KEY REFERENCES Users(UserID) ON DELETE NO ACTION,
	Liked BIT NOT NULL,
	CONSTRAINT ReactionPK PRIMARY KEY (PostID, UserID)
);
CREATE TABLE BannedUsers (
	UserID INT IDENTITY(1, 1) PRIMARY KEY,
	Username NVARCHAR(25) UNIQUE NOT NULL,
	Email NVARCHAR(100) UNIQUE NOT NULL,
);