DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS ReportedPosts;
DROP TABLE IF EXISTS Reaction;
CREATE TABLE Users (
	UserID INT IDENTITY(1, 1) PRIMARY KEY,
	Username NVARCHAR(25) UNIQUE NOT NULL,
	Email NVARCHAR(100) UNIQUE NOT NULL,
	Pwd NVARCHAR(100) NOT NULL,
	Pais NVARCHAR(30),
	Ciudad NVARCHAR(50),
	Nombre NVARCHAR(100)
);
CREATE TABLE Posts (
	PostID INT IDENTITY(1, 1) PRIMARY KEY,
	UserID INT FOREIGN KEY REFERENCES Users(UserID) NOT NULL,
	-- Username NVARCHAR(25) FOREIGN KEY REFERENCES Users(Username),
	Likes INT NOT NULL,
	Dislikes INT NOT NULL,
	Img IMAGE NOT NULL,
	UploadDate DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE TABLE ReportedPosts (
	PostID INT FOREIGN KEY REFERENCES Posts(PostID),
	Reporter INT FOREIGN KEY REFERENCES Users(UserID),
	Cat INT NOT NULL,
	CONSTRAINT ReportPK PRIMARY KEY (PostID, Reporter)
);
CREATE TABLE Reaction (
	PostID INT FOREIGN KEY REFERENCES Posts(PostID),
	UserID INT FOREIGN KEY REFERENCES Users(UserID),
	Liked BIT NOT NULL,
	CONSTRAINT ReactionPK PRIMARY KEY (PostID, UserID)
);