//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PawPalsApp.Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PawPalsApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Settings.
        /// </summary>
        internal static string AccSettings {
            get {
                return ResourceManager.GetString("AccSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All About Diet.
        /// </summary>
        internal static string AllAboutDiet {
            get {
                return ResourceManager.GetString("AllAboutDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Care.
        /// </summary>
        internal static string Care {
            get {
                return ResourceManager.GetString("Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sterilized cats are more likely to be obese, since by not mating, their metabolism and physical activity decrease. Forsterilized felines and those that suffer from obesity, there are special diets that will help them in the battle against the scale. Commercial brands such as Criadores, Affinity Advance and Royal Canin, among others, which you will find at the best price in Tiendanimal, have a special range of feed for sterilized and overweight cats that will be the ideal alternative for your pet to maintain [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CatsDiet {
            get {
                return ResourceManager.GetString("CatsDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact us.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CuteOMeter.
        /// </summary>
        internal static string CuteOMeter {
            get {
                return ResourceManager.GetString("CuteOMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Account.
        /// </summary>
        internal static string DelAcc {
            get {
                return ResourceManager.GetString("DelAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure do you want to delete your account?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure do you want to delete your account?.
        /// </summary>
        internal static string DelQuestion {
            get {
                return ResourceManager.GetString("DelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animals need a proper diet and we pride ourselves on having the best to advise owners..
        /// </summary>
        internal static string DescAllAboutDiet {
            get {
                return ResourceManager.GetString("DescAllAboutDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diet.
        /// </summary>
        internal static string Diet {
            get {
                return ResourceManager.GetString("Diet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The BARF is to feed the dogs in an appropriate way. Their goal is to maximize the health, longevity and reproductive capacity of dogs and, by doing so, minimize the need for veterinary intervention. How to properly feed a dog? Giving them the diet they evolved and are designed to eat. Artificial grain-based diets cause countless health problems. They are not what your dog was programmed to eat during his long evolutionary process. A biologically appropriate diet for a dog is one that consists of whole raw f [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string DogsDiet {
            get {
                return ResourceManager.GetString("DogsDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exercise.
        /// </summary>
        internal static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hygiene.
        /// </summary>
        internal static string Hygiene {
            get {
                return ResourceManager.GetString("Hygiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your city.
        /// </summary>
        internal static string NomCity {
            get {
                return ResourceManager.GetString("NomCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your country.
        /// </summary>
        internal static string NomCountry {
            get {
                return ResourceManager.GetString("NomCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal name.
        /// </summary>
        internal static string Personal_name {
            get {
                return ResourceManager.GetString("Personal name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy policy.
        /// </summary>
        internal static string PrivaPol {
            get {
                return ResourceManager.GetString("PrivaPol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nut-based diet. The vast majority of rodents love nuts.
        ///Squirrels are the main consumers of nuts.Rats, mice and porcupines are also great addicts of this type of food.
        ///
        ///Diets for carnivores
        ///Some rodents eat meat. Rats are especially prone to eating meat and fish. Rats are capable of digesting rotting meat and consuming remnants of human waste. They don&apos;t let any opportunity escape!
        ///
        ///Diets with fruits and berries \n In wild and natural environments, rodents eat fruits and berries, which are the foods t [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RodentDiet {
            get {
                return ResourceManager.GetString("RodentDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an option.
        /// </summary>
        internal static string SelApar {
            get {
                return ResourceManager.GetString("SelApar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy, information, management.
        /// </summary>
        internal static string SettingAccount {
            get {
                return ResourceManager.GetString("SettingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support, privacy policy .
        /// </summary>
        internal static string SettingHelp {
            get {
                return ResourceManager.GetString("SettingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diet for obese and sterilized cats.
        /// </summary>
        internal static string TitleCatsDiet {
            get {
                return ResourceManager.GetString("TitleCatsDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What is the BARF diet for dogs?.
        /// </summary>
        internal static string TitleDogsDiet {
            get {
                return ResourceManager.GetString("TitleDogsDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What are the diets of rodents?.
        /// </summary>
        internal static string TitleRodentDiet {
            get {
                return ResourceManager.GetString("TitleRodentDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Manual.
        /// </summary>
        internal static string UserManual {
            get {
                return ResourceManager.GetString("UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
